#!/usr/bin/env bash
scroll_page(){
	cat <<-EOF
		let waitload = new Promise(function(res) {
			function loadimages() {
				setTimeout(function() {
					if(typeof images[i] != 'undefined'){
						images[i].scrollIntoView();
					}
					if(i++ < images.length) {
						loadimages(images);
					} else {
						res();
					}
				}, 50)
			}
			let i = 0, images = document.getElementsByTagName('img');
			loadimages(images);
		});

		let body = document.body, html = document.documentElement;
		let height = Math.max(body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight);

		waitload.then(function(){
			g = document.createElement('div');
			g.setAttribute('id', 'screengrabber-pageisloaded');
			document.body.appendChild(g);
		});

		return height;
	EOF
}

page_loaded(){
	[[ $(exec_script "if(document.getElementById('screengrabber-pageisloaded')) return true;" | jq -r '.value') == true ]]
}

trap -- 'killall chromedriver chromium; exit' ERR 0 1 2 3 6 13 14 15

{
	ps -C chromedriver || setsid -f chromedriver
	pushd "${HOME}/git/shellnium"
	. lib/selenium.sh --headless
	popd
} &>/dev/null

for url; do
	echo "Screenshotting ${url}"
	navigate_to "${url}"
	page_height=$(exec_script "$(scroll_page)" | jq -r '.value')
	until page_loaded; do sleep 1; done
	set_window_rect 0 0 1920 "${page_height}"
	screenshot "screenshot_$((i++)).png"
done
